background_opacity 0.9
background_image ~/.config/kitty/bg-blurred-darker.png
background_image_layout scaled


# Font settings
font_family BlexMono Nerd Font
bold_font auto
italic_font auto
bold_italic_font auto
font_size 11.0
adjust_line_height 100%
font_features none

# Cursor settings
cursor_blink_interval 0

# Window decorations
# Set to "no" to display a top bar for dragging and moving the window
# Use "smart" to hide decorations when maximized but show in windowed mode
hide_window_decorations no

# Set scrollback lines maximum
scrollback_lines 100000

# Automatically copy text to the clipboard when selected
copy_on_select yes

# Theme settings
include catppuccin-theme.conf
